import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Nav from '@/components/organisms/nav';
import { Toaster } from '@/components/ui/toaster';
import Providers from '@/lib/query-provider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-4 lg:px-24  xl:px-48">
          <Providers>
            <Nav />
            {children}
            <Toaster />
          </Providers>
        </div>
      </body>
    </html>
  );
}
